### ISSUE TITLE
No data graph

### ISSUE THREAD

**Issue by andresmann93** [lbussy/brewpi-www-rmx#30]
Hi lbussy,

I was hopping you could help me. I am running BrewPi Remix 0.5.3.0 everything is working fine except i am not able to see the graph. I have tried reinstalling brewpi as well as running /home/brewpi/tools/fixPermissions.sh with no luck.

![Annotation 2019-07-13 161647](https://user-images.githubusercontent.com/52848751/61177407-c07c8780-a589-11e9-85a1-b4b3dd1ddd16.png)

**Comment by lbussy** [comment]
Delayed again so I busted out my RPi Zero here in the airport.  :)

Pushed a fix for this to the devel branch.  If you'd like, you can copy the [js/beer-chart.js](https://github.com/brewpi-remix/brewpi-www-rmx/blob/devel/js/beer-chart.js) file to your /var/www/html/js/beer-chart.js file and then re-run doPerms.sh.  If you are not familiar with just getting one file from here, you can go to the [raw version](https://raw.githubusercontent.com/brewpi-remix/brewpi-www-rmx/devel/js/beer-chart.js) and copy/paste.

I was able to re-create and then fix the error.  The changes themselves  were trivial and _should not_ break anything else, but this is not fully tested.

**Comment by andresmann93** [comment]
hahah that's awesome!
it looks like i don't have permission to edit that file

**Comment by andresmann93** [comment]
I was able to figure it out. I'm rebooting now.

**Comment by andresmann93** [comment]
I have data!!
Thank you for all your help.

**Comment by lbussy** [comment]
Excellent!  Thanks for letting me know about it.   I’ll finish testing and float this tomorrow.

**Comment by lbussy** [comment]
Regression finished.
